crop_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crop_stats.urls')),
    path('api/', include('crop_stats.api.urls')),
]

crop_stats/api/urls.py
from django.urls import path
from .views import CropStatAPIView

urlpatterns = [
    path('', CropStatAPIView.as_view()),
]

crop_stats/urls.py
from django.urls import path, include
from .views import CropStatsView, graph_view

app_name = 'crop_stats'

urlpatterns = [
    path('', CropStatsView.as_view(), name='home'),
    path('graph/', graph_view, name='graph'),
]

crop_stats/models.py
from django.db import models


class CropStats(models.Model):
    time = models.DateTimeField(auto_now_add=True)
    temperature = models.IntegerField()
    humidity = models.IntegerField()
    sunlight = models.IntegerField()
    crop_health = models.SmallIntegerField(null=True, blank=True)

    def __str__(self):
        return f'Recorded at {self.time}'

crop_stats/api/views.py
from rest_framework.generics import CreateAPIView

from .serializers import CropStatSerializer
from crop_stats.models import CropStats


class CropStatAPIView(CreateAPIView):
    serializer_class = CropStatSerializer

    def post(self, *args, **kwargs):
        return self.create(*args, **kwargs)

crop_stats/views.py
from django.views.generic import ListView, View
from django.shortcuts import render


from .models import CropStats


class CropStatsView(ListView):
    model = CropStats
    paginate_by = 20
    template_name = 'crop_stats/crop_stats_home.html'
    context_object_name = 'stat_objs'


def graph_view(request):
    crop_stats = CropStats.objects.all().order_by('crop_health')
    temperature = []
    humidity = []
    sunlight = []
    crop_health = []
    for crop_stat in crop_stats:
        temperature.append(crop_stat.temperature)
        humidity.append(crop_stat.humidity)
        sunlight.append(crop_stat.sunlight)
        crop_health.append(crop_stat.crop_health)
    context = {
        'temperature': temperature,
        'humidity': humidity,
        'sunlight': sunlight,
        'crop_health': crop_health,
    }
    return render(request, 'crop_stats/graph_view.html', context=context)

crop_stats/templates/crop_stats/crop_stats_home.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid m-3">
    <table class="table table-dark">
      <thead>
        <tr>
          <th scope="col">Sr. No.</th>
          <th scope="col">Time</th>
          <th scope="col">Humidity</th>
          <th scope="col">Temperature</th>
          <th scope="col">Sunlight</th>
          <th scope="col">Crop Health</th>
        </tr>
      </thead>
      <tbody>
        {% for stat_obj in stat_objs %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td>{{ stat_obj.time }}</td>
              <td>{{ stat_obj.humidity }}</td>
              <td>{{ stat_obj.temperature }}</td>
              <td>{{ stat_obj.sunlight }}</td>
              <td class="
              {% if stat_obj.crop_health <= 3 %}
                bg-danger
              {% elif stat_obj.crop_health > 3 and stat_obj.crop_health < 7 %}
                bg-primary
              {% elif stat_obj.crop_health > 7 and stat_obj.crop_health <= 10 %}
                bg-success
              {% endif %}">
              {% if stat_obj.crop_health <= 3 %}
                Worse than Before
              {% elif stat_obj.crop_health > 3 and stat_obj.crop_health < 7 %}
                Same as Before
              {% elif stat_obj.crop_health > 7 and stat_obj.crop_health <= 10 %}
                Better than Before
              {% endif %}
              </td>
            </tr>
        {% endfor %}
      </tbody>
    </table>
</div>
{% endblock %}

crop_stats/templates/crop_stats/graph_view.html
{% extends 'base.html' %}
{% block content %}
    <div id="container" style="width:75%;margin:auto;">
        <div class="row">
            <div class="col-12">
                <h5>Temperature and Humidity's Relation to Crop Health</h5>
                <br>
                <canvas id="temperature-chart"></canvas>
            </div>
            <div class="col-12">
                <hr>
            </div>
            <div class="col-12">
                <h5>Sunlight and Crop health's Relation</h5>
                <br>
                <canvas id="sun-chart"></canvas>
            </div>
        </div>

    </div>

{% endblock %}
{% block script %}
<script>
    window.onload = () => {
      var temp_ctx = document.getElementById('temperature-chart').getContext('2d');
      var sun_ctx = document.getElementById('sun-chart').getContext('2d');
      window.tempLine = new Chart(temp_ctx, {
          type: 'line',
          data: {
            datasets: [
                {
                    data: {{ temperature|safe }},
                    label: 'Crop-Health To Temperature',
                    borderColor: '#FF0000',

                },
                {
                    data: {{ humidity|safe }},
                    label: 'Crop-Health To Humidity',
                    borderColor: '#34A56F',
                },
            ],
            labels: {{ crop_health|safe }},
            fill:false,
          },
          options: {
            responsive: true,
            scales:{
                y: {
                    title: {
                        display:true,
                        text:'Temp/Humidity Value'
                    },
                    min:0,
                    max:100,
                    ticks:{
                        stepSize: 10,
                    }
                },
                x: {
                    title: {
                        display:true,
                        text:'Crop Health Index',
                    },
                }
            }
          }
      });
      window.sunLine = new Chart(sun_ctx, {
          type: 'line',
          data: {
            datasets: [
                {
                    data: {{ sunlight|safe }},
                    label: 'Crop-Health To Sunlight',
                    borderColor: '#FF0000',
                },
            ],
            labels: {{ crop_health|safe }},
            fill:false,
          },
          options: {
            responsive: true,
            scales:{
                y: {
                    title: {
                        display:true,
                        text:'Sunlight Value'
                    },
<!--                    min:0,-->
<!--                    max:100,-->
<!--                    ticks:{-->
<!--                        stepSize: 10,-->
<!--                    }-->
                },
                x: {
                    title: {
                        display:true,
                        text:'Crop Health Index',
                    },
                }
            }
          }
      });
    };
    </script>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <link rel="shortcut icon" href="">
      <!-- Bootstrap/CSS Files(.css)-->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet">

      <title>Crop Health Portal</title>
      {% block script %}
      {% endblock %}
  </head>
  <header>
      {% block navbar %}
          {% include 'navbar.html' %}
      {% endblock %}
  </header>
  <body>
    <div class="row my-5">
        {% block content %}
        {% endblock %}
    </div>
  </body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.7.1/dist/chart.min.js"></script>

</html>

templates/navbar.html
{% url 'crop_stats:graph' as graph %}
{% url 'crop_stats:home' as home %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">CropManagement</a>
        <div class="nav" id="navbarContent">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == home %}active{% endif %}" href="{% url 'crop_stats:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == graph %}active{% endif %}" href="{% url 'crop_stats:graph' %}">Graphs</a>
                </li>
            </ul>
        </div>
    </div>
</nav>